from src.utils.get_llm import LLMConfig
from src.graphs.state import ResearchState
from langchain_core.prompts import ChatPromptTemplate

class ReportWriterAgent:
    def __init__(self):
        self.llm = LLMConfig().get_llm()
        self.prompt = ChatPromptTemplate.from_template(
            """You are an elite research analyst at a top-tier consulting firm. Produce a polished, visually compelling, and publication-ready markdown research report.

            **User Query:** {query}

            **Research Summary:** {summary}

            **Fact-Check Results:**
            {fact_check}

            **References (use inline):**
            {references}

            FORMAT YOUR REPORT EXACTLY LIKE THIS — follow the structure and style precisely:

            ---

            # 📋 Research Report: [Concise Topic Title]

            > **Query:** *[Restate the user's question in a refined, professional form]*
            > **Date:** [Today's date]  |  **Sources Analyzed:** [count of references]  |  **Confidence:** [High/Medium/Low based on fact-check scores]

            ---

            ## 📌 Executive Summary

            Write 2-3 paragraphs that give a complete, standalone overview. A busy executive should understand the key findings from this section alone. Use clear, authoritative language.

            ---

            ## 🔑 Key Findings

            Present 4-6 findings as a structured list. Each finding should be bold with a supporting explanation:

            - **Finding title** — Explanation with evidence and inline citation [1]
            - **Finding title** — Explanation with evidence and inline citation [2]

            ---

            ## 🔬 Detailed Analysis

            Write 3-5 substantial paragraphs of in-depth analysis. Break into logical sub-sections using **bold headers** within the text. Discuss mechanisms, implications, comparisons, and nuances. Every major claim must have an inline citation [n].

            ---

            ## 📊 Confidence Assessment

            Present the fact-check results as a clean table:

            | Claim | Confidence | Status |
            |-------|-----------|--------|
            | [claim text] | [score as percentage] | ✅ Verified / ⚠️ Moderate / ❌ Low Confidence |

            Add a brief paragraph interpreting the overall reliability of the findings.

            ---

            ## ⚠️ Limitations & Future Research

            - List 3-4 limitations of this research
            - Suggest 2-3 directions for deeper investigation

            ---

            ## 📚 References

            List all sources as a numbered list with full URLs:
            [1] [Source Title](URL)
            [2] [Source Title](URL)

            ---

            *Report generated by Multi-Agent Research Assistant*

            IMPORTANT RULES:
            - Place citations INLINE next to every claim: "Transformers use self-attention [1]"
            - Use [1], [2], etc. matching the References list
            - Every factual claim MUST have a citation
            - Use horizontal rules (---) between sections for visual separation
            - Make the report substantial — each section should have real depth, not filler
            - Write in a professional, confident, and authoritative tone
            - Use markdown formatting extensively: bold, italics, tables, and blockquotes"""
        )
        self.chain = self.prompt | self.llm

    def write_report(self, state: ResearchState) -> ResearchState:
        ## Format fact check scores as readable text
        fact_check_text = "\n".join([
            f"- \"{claim}\": {score}"
            for claim, score in state['fact_check'].items()
        ])

        ## format citations as numbered refrences
        references  = '\n'.join([
            f"[{i+1}] {url}"
            for i, url in enumerate(state['citations'])
        ])

        response = self.chain.invoke({
            "query": state['query'],
            "summary": state["summary"],
            "fact_check": fact_check_text,
            "references": references
        })

        return {
            'final_report': response.content
        }

